/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    projects: Project;
    categories: Category;
    families: Family;
    news: News;
    symbols: Symbol;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    families: FamiliesSelect<false> | FamiliesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    symbols: SymbolsSelect<false> | SymbolsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  type?: ('image' | 'video' | 'document') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  description?: string | null;
  families?: (string | null) | Family;
  images: string | Media;
  datasheetPdf?: (string | null) | Media;
  photometryLdt?: (string | null) | Media;
  photometryIes?: (string | null) | Media;
  bimRevit?: (string | null) | Media;
  techDocControlGear?: (string | null) | Media;
  techDocContainingProduct?: (string | null) | Media;
  techDocLightSource?: (string | null) | Media;
  colour?: string | null;
  power?: string | null;
  colourTemperature?: string | null;
  /**
   * Specifications will be fetched from the general_data.luminaire collection.
   */
  specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families".
 */
export interface Family {
  id: string;
  name: string;
  description: string;
  categories: (string | Category)[];
  media: (string | Media)[];
  products?: (string | Product)[] | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  symbols?: (string | Symbol)[] | null;
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            content?: string | null;
            image?: (string | null) | Media;
            linkText?: string | null;
            linkUrl?: string | null;
            layout?: ('grid' | 'split-left' | 'split-right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorial';
          }
        | {
            title: string;
            subtitle?: string | null;
            products: (string | Product)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlightProducts';
          }
        | {
            title: string;
            subtitle?: string | null;
            projects: (string | Project)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'inspiration';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  parent?: (string | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symbols".
 */
export interface Symbol {
  id: string;
  name: string;
  icon?: (string | null) | Media;
  isHighlighted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  description?: string | null;
  location?: string | null;
  images: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * e.g. MATTER SMART HOME, ECO SYSTEM, NEW ARRIVALS
   */
  category: string;
  publishDate: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image: string | Media;
  linkText?: string | null;
  linkUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'families';
        value: string | Family;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'symbols';
        value: string | Symbol;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  families?: T;
  images?: T;
  datasheetPdf?: T;
  photometryLdt?: T;
  photometryIes?: T;
  bimRevit?: T;
  techDocControlGear?: T;
  techDocContainingProduct?: T;
  techDocLightSource?: T;
  colour?: T;
  power?: T;
  colourTemperature?: T;
  specifications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  location?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families_select".
 */
export interface FamiliesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  categories?: T;
  media?: T;
  products?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  symbols?: T;
  layout?:
    | T
    | {
        editorial?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              image?: T;
              linkText?: T;
              linkUrl?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        highlightProducts?:
          | T
          | {
              title?: T;
              subtitle?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        inspiration?:
          | T
          | {
              title?: T;
              subtitle?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  publishDate?: T;
  summary?: T;
  content?: T;
  image?: T;
  linkText?: T;
  linkUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symbols_select".
 */
export interface SymbolsSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  isHighlighted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  layout?:
    | (
        | {
            slides?:
              | {
                  title: string;
                  subtitle: string;
                  description?: string | null;
                  image: string | Media;
                  ctaText?: string | null;
                  ctaLink?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            subtitle?: string | null;
            categories?:
              | {
                  number: string;
                  title: string;
                  description?: string | null;
                  parameterLabel?: string | null;
                  parameterValue: string;
                  linkUrl: string;
                  linkText?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoriesGrid';
          }
        | {
            title: string;
            subtitle?: string | null;
            content?: string | null;
            image?: (string | null) | Media;
            linkText?: string | null;
            linkUrl?: string | null;
            layout?: ('grid' | 'split-left' | 'split-right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorial';
          }
        | {
            title: string;
            subtitle?: string | null;
            products: (string | Product)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlightProducts';
          }
        | {
            title: string;
            subtitle?: string | null;
            projects: (string | Project)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'inspiration';
          }
        | {
            title: string;
            subtitle?: string | null;
            source?: ('latest' | 'custom') | null;
            featuredNews?: (string | News)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              slides?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    description?: T;
                    image?: T;
                    ctaText?: T;
                    ctaLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoriesGrid?:
          | T
          | {
              title?: T;
              subtitle?: T;
              categories?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    parameterLabel?: T;
                    parameterValue?: T;
                    linkUrl?: T;
                    linkText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        editorial?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              image?: T;
              linkText?: T;
              linkUrl?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        highlightProducts?:
          | T
          | {
              title?: T;
              subtitle?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        inspiration?:
          | T
          | {
              title?: T;
              subtitle?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              subtitle?: T;
              source?: T;
              featuredNews?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}