/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    projects: Project;
    categories: Category;
    families: Family;
    news: News;
    symbols: Symbol;
    skus: Skus;
    videos: Video;
    awards: Award;
    catalogs: Catalog;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    families: FamiliesSelect<false> | FamiliesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    symbols: SymbolsSelect<false> | SymbolsSelect<true>;
    skus: SkusSelect<false> | SkusSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    catalogs: CatalogsSelect<false> | CatalogsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Optional description or caption for this media item (displayed below image on family pages)
   */
  description?: string | null;
  type?: ('image' | 'video' | 'document') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * Select which site(s) this product should be displayed on.
   */
  sites: ('international' | 'hk')[];
  description?: string | null;
  families?: (string | null) | Family;
  images: string | Media;
  datasheetPdf?: (string | null) | Media;
  photometryLdt?: (string | null) | Media;
  photometryIes?: (string | null) | Media;
  lightSpectrumGraph?: (string | null) | Media;
  lineDrawing?: (string | null) | Media;
  photometricPolarDiagram?: (string | null) | Media;
  beamAngleDiagram?: (string | null) | Media;
  techDocControlGear?: (string | null) | Media;
  techDocContainingProduct?: (string | null) | Media;
  techDocLightSource?: (string | null) | Media;
  colour?: string | null;
  power?: string | null;
  colourTemperature?: string | null;
  /**
   * Specifications will be fetched from the general_data.luminaire collection.
   */
  specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families".
 */
export interface Family {
  id: string;
  name: string;
  description: string;
  categories: (string | Category)[];
  media: (string | Media)[];
  products?: (string | Product)[] | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        application: string;
        id?: string | null;
      }[]
    | null;
  symbols?: (string | Symbol)[] | null;
  /**
   * Uploaded PDF for Market Surveillance Dismantle Instruction. Automatically merged into Technical Document - Light Source and Technical Document - Control Gear for all products in this family.
   */
  dismantleInstructionPdf?: (string | null) | Media;
  /**
   * Select which parameters/specifications are active for this family. This controls both the visible dropdown filters and the Technical Configuration spreadsheet columns.
   */
  selectedParameters?:
    | (
        | 'mmCode'
        | 'modelNo'
        | 'colour'
        | 'wattage'
        | 'luminousFlux'
        | 'colourTemperature'
        | 'cri'
        | 'efficacy'
        | 'ip'
        | 'connector'
        | 'lampBase'
        | 'voltage'
      )[]
    | null;
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            content?: string | null;
            image?: (string | null) | Media;
            linkText?: string | null;
            linkUrl?: string | null;
            layout?: ('grid' | 'split-left' | 'split-right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorial';
          }
        | {
            title: string;
            subtitle?: string | null;
            products: (string | Product)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlightProducts';
          }
        | {
            title: string;
            subtitle?: string | null;
            projects: (string | Project)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'inspiration';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            video?: (string | null) | Media;
            mobileVideo?: (string | null) | Media;
            captions?:
              | {
                  title: string;
                  content?: string | null;
                  align?: ('left' | 'center' | 'right') | null;
                  startPercent?: number | null;
                  endPercent?: number | null;
                  linkText?: string | null;
                  linkUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'scrollVideo';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  parent?: (string | null) | Category;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symbols".
 */
export interface Symbol {
  id: string;
  name: string;
  icon?: (string | null) | Media;
  isHighlighted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title if left blank)
   */
  slug: string;
  description?: string | null;
  location: string;
  applicationType: 'hospitality' | 'retail' | 'residential' | 'commercial';
  listImage: string | Media;
  bannerImage: string | Media;
  contentRows?:
    | {
        layoutType: 'full' | 'one-third-two-thirds' | 'two-thirds-one-third' | 'half-half';
        leftImage: string | Media;
        rightImage?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * e.g. MATTER SMART HOME, ECO SYSTEM, NEW ARRIVALS
   */
  category: string;
  publishDate: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image: string | Media;
  linkText?: string | null;
  linkUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skus".
 */
export interface Skus {
  id: string;
  name: string;
  product: string | Product;
  modelNumber?: string | null;
  colour?: string | null;
  specialFeatures?: string | null;
  wattage?: string | null;
  lampBase?: string | null;
  colourTemperature?: string | null;
  voltage?: string | null;
  connector?: string | null;
  ip?: string | null;
  eanBarcode?: string | null;
  innerBoxItf?: string | null;
  outerBoxItf?: string | null;
  packingMethod?: string | null;
  remark?: string | null;
  photometryLdt?: (string | null) | Media;
  photometryIes?: (string | null) | Media;
  lightSpectrumGraph?: (string | null) | Media;
  lineDrawing?: (string | null) | Media;
  photometricPolarDiagram?: (string | null) | Media;
  beamAngleDiagram?: (string | null) | Media;
  specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Pasted YouTube video URL (e.g., https://www.youtube.com/watch?v=E8vXpMvPILk or https://youtu.be/E8vXpMvPILk)
   */
  youtubeLink: string;
  /**
   * Auto-extracted YouTube video ID
   */
  youtubeId: string;
  category: 'Corporate' | 'Smart Lighting' | 'Installation' | 'Case Study' | 'Sustainability' | 'Technical';
  /**
   * e.g. 3:42, 4:15, or 6:28
   */
  duration: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: string;
  title: string;
  /**
   * e.g. 2025, 2013-17
   */
  year: string;
  /**
   * e.g. Hong Kong Commercial Daily, BATIBOUW, Belgium
   */
  institution: string;
  /**
   * Awards category to filter by on the website
   */
  category: 'environmental' | 'quality' | 'technological' | 'other';
  /**
   * Image file for the award brand logo
   */
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs".
 */
export interface Catalog {
  id: string;
  title: string;
  description?: string | null;
  category: 'general' | 'lamps' | 'indoor' | 'outdoor' | 'technical';
  catalogFile: string | Media;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'families';
        value: string | Family;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'symbols';
        value: string | Symbol;
      } | null)
    | ({
        relationTo: 'skus';
        value: string | Skus;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'awards';
        value: string | Award;
      } | null)
    | ({
        relationTo: 'catalogs';
        value: string | Catalog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  description?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  sites?: T;
  description?: T;
  families?: T;
  images?: T;
  datasheetPdf?: T;
  photometryLdt?: T;
  photometryIes?: T;
  lightSpectrumGraph?: T;
  lineDrawing?: T;
  photometricPolarDiagram?: T;
  beamAngleDiagram?: T;
  techDocControlGear?: T;
  techDocContainingProduct?: T;
  techDocLightSource?: T;
  colour?: T;
  power?: T;
  colourTemperature?: T;
  specifications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  location?: T;
  applicationType?: T;
  listImage?: T;
  bannerImage?: T;
  contentRows?:
    | T
    | {
        layoutType?: T;
        leftImage?: T;
        rightImage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families_select".
 */
export interface FamiliesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  categories?: T;
  media?: T;
  products?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        application?: T;
        id?: T;
      };
  symbols?: T;
  dismantleInstructionPdf?: T;
  selectedParameters?: T;
  layout?:
    | T
    | {
        editorial?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              image?: T;
              linkText?: T;
              linkUrl?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        highlightProducts?:
          | T
          | {
              title?: T;
              subtitle?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        inspiration?:
          | T
          | {
              title?: T;
              subtitle?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        scrollVideo?:
          | T
          | {
              title?: T;
              subtitle?: T;
              video?: T;
              mobileVideo?: T;
              captions?:
                | T
                | {
                    title?: T;
                    content?: T;
                    align?: T;
                    startPercent?: T;
                    endPercent?: T;
                    linkText?: T;
                    linkUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  publishDate?: T;
  summary?: T;
  content?: T;
  image?: T;
  linkText?: T;
  linkUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symbols_select".
 */
export interface SymbolsSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  isHighlighted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skus_select".
 */
export interface SkusSelect<T extends boolean = true> {
  name?: T;
  product?: T;
  modelNumber?: T;
  colour?: T;
  specialFeatures?: T;
  wattage?: T;
  lampBase?: T;
  colourTemperature?: T;
  voltage?: T;
  connector?: T;
  ip?: T;
  eanBarcode?: T;
  innerBoxItf?: T;
  outerBoxItf?: T;
  packingMethod?: T;
  remark?: T;
  photometryLdt?: T;
  photometryIes?: T;
  lightSpectrumGraph?: T;
  lineDrawing?: T;
  photometricPolarDiagram?: T;
  beamAngleDiagram?: T;
  specifications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  youtubeLink?: T;
  youtubeId?: T;
  category?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  institution?: T;
  category?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs_select".
 */
export interface CatalogsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  catalogFile?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  international?: {
    layout?:
      | (
          | {
              slides?:
                | {
                    title: string;
                    subtitle: string;
                    description?: string | null;
                    image: string | Media;
                    ctaText?: string | null;
                    ctaLink?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              title: string;
              subtitle?: string | null;
              categories?:
                | {
                    title: string;
                    image?: (string | null) | Media;
                    description?: string | null;
                    linkUrl: string;
                    linkText?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'categoriesGrid';
            }
          | {
              title: string;
              subtitle?: string | null;
              content?: string | null;
              image?: (string | null) | Media;
              linkText?: string | null;
              linkUrl?: string | null;
              layout?: ('grid' | 'split-left' | 'split-right') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'editorial';
            }
          | {
              title: string;
              subtitle?: string | null;
              products: (string | Product)[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'highlightProducts';
            }
          | {
              title: string;
              subtitle?: string | null;
              projects: (string | Project)[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'inspiration';
            }
          | {
              title: string;
              subtitle?: string | null;
              source?: ('latest' | 'custom') | null;
              featuredNews?: (string | News)[] | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'news';
            }
        )[]
      | null;
  };
  hk?: {
    layout?:
      | (
          | {
              slides?:
                | {
                    title: string;
                    subtitle: string;
                    description?: string | null;
                    image: string | Media;
                    ctaText?: string | null;
                    ctaLink?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              title: string;
              subtitle?: string | null;
              categories?:
                | {
                    title: string;
                    image?: (string | null) | Media;
                    description?: string | null;
                    linkUrl: string;
                    linkText?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'categoriesGrid';
            }
          | {
              title: string;
              subtitle?: string | null;
              content?: string | null;
              image?: (string | null) | Media;
              linkText?: string | null;
              linkUrl?: string | null;
              layout?: ('grid' | 'split-left' | 'split-right') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'editorial';
            }
          | {
              title: string;
              subtitle?: string | null;
              products: (string | Product)[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'highlightProducts';
            }
          | {
              title: string;
              subtitle?: string | null;
              projects: (string | Project)[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'inspiration';
            }
          | {
              title: string;
              subtitle?: string | null;
              source?: ('latest' | 'custom') | null;
              featuredNews?: (string | News)[] | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'news';
            }
        )[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  international?:
    | T
    | {
        layout?:
          | T
          | {
              hero?:
                | T
                | {
                    slides?:
                      | T
                      | {
                          title?: T;
                          subtitle?: T;
                          description?: T;
                          image?: T;
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              categoriesGrid?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    categories?:
                      | T
                      | {
                          title?: T;
                          image?: T;
                          description?: T;
                          linkUrl?: T;
                          linkText?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              editorial?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    content?: T;
                    image?: T;
                    linkText?: T;
                    linkUrl?: T;
                    layout?: T;
                    id?: T;
                    blockName?: T;
                  };
              highlightProducts?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    products?: T;
                    id?: T;
                    blockName?: T;
                  };
              inspiration?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    projects?: T;
                    id?: T;
                    blockName?: T;
                  };
              news?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    source?: T;
                    featuredNews?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  hk?:
    | T
    | {
        layout?:
          | T
          | {
              hero?:
                | T
                | {
                    slides?:
                      | T
                      | {
                          title?: T;
                          subtitle?: T;
                          description?: T;
                          image?: T;
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              categoriesGrid?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    categories?:
                      | T
                      | {
                          title?: T;
                          image?: T;
                          description?: T;
                          linkUrl?: T;
                          linkText?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              editorial?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    content?: T;
                    image?: T;
                    linkText?: T;
                    linkUrl?: T;
                    layout?: T;
                    id?: T;
                    blockName?: T;
                  };
              highlightProducts?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    products?: T;
                    id?: T;
                    blockName?: T;
                  };
              inspiration?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    projects?: T;
                    id?: T;
                    blockName?: T;
                  };
              news?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    source?: T;
                    featuredNews?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}